name: 기능 추가 또는 버그 수정
description: 새로운 기능 추가 또는 버그 수정을 위한 이슈를 생성합니다.
title: "[TYPE]: 간결한 제목 #이슈번호"
labels: ["enhancement", "bug"]
body:
  - type: dropdown
    id: type
    attributes:
      label: 커밋 타입 (Type)
      description: 이 작업의 커밋 타입을 선택하세요.
      options:
        - feat (새로운 기능 추가)
        - fix (버그 수정)
        - design (CSS 등 사용자 UI 디자인 변경)
        - docs (문서 변경)
        - chore (빌드 설정, 의존성, 환경 설정 변경)
        - refactor (코드 리팩토링 혹은 성능 개선)
        - test (테스트 코드 추가 또는 수정)
        - comment (필요한 주석 추가 및 수정)
        - style (코드 포맷팅)
        - remove (파일, 기능, 의존성 제거)
        - ci (CI 설정 변경)
        - cd (CD 설정 변경)
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 상세 설명 (Body)
      description: 이 작업에 대한 자세한 설명을 작성해주세요. 문제점, 해결 방안, 변경 사항 등을 포함합니다.
      placeholder: |
        - 문제점 (버그인 경우):
        - 해결 방안 / 변경 사항 (기능 추가 또는 수정인 경우):
        - 영향 범위:
    validations:
      required: true
  - type: checkboxes
    id: breaking_change
    attributes:
      label: 브레이킹 체인지 (Breaking Change)
      description: 기존 버전과 호환되지 않는 변경사항이 있습니까?
      options:
        - label: 예, 브레이킹 체인지가 있습니다.
          required: false
  - type: textarea
    id: breaking_change_description
    attributes:
      label: 브레이킹 체인지 상세 (Breaking Change Details - 위에 '예' 선택 시 작성)
      description: 브레이킹 체인지에 대한 설명을 작성해주세요.
      placeholder: |
        예시:
        `/api/v1/auth` 엔드포인트가 `/api/v2/auth`로 변경되었습니다.
