spring:
  application:
    name: luigi-log-server
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true

server:
  port: 8080

jwt:
  secret: my-secret-key-for-jwt-token-generation-must-be-long-enough-for-security
  access-token-validity: 86400000  # 24 hours
  refresh-token-validity: 2592000000  # 30 days

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    cloud.luigi99.blog: DEBUG
    org.springframework.security: DEBUG